# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fffc3d80efcda9e509e4e2df87ab9c8584ffc7825a5d352511560097c3dbbfd33655847c589464f6c4a61a68a39770eb997ef649a562511b983715c07bf15bbf

test:
  secret_key_base: bac8dec0bb4d219aa7a5f28b4dc10fa2267417ba65e01b4db3d46739ddf9af0fedf1beade3cc66317d8090ea66d388b66fb53ff30c6216e791afcaf74daafd19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
